version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - third_party
    - bin

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    
    # Ignore generated files
    - path: ".*\\.pb\\.go$"
      linters:
        - all
    
    - path: ".*_gen\\.go$"
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0
