-- Migration: Change employee ID from BIGSERIAL to UUID
-- This is a destructive migration - data will be regenerated with new UUIDs

BEGIN;

-- Drop existing foreign key constraints (none currently, but for future)
-- ALTER TABLE IF EXISTS other_table DROP CONSTRAINT IF EXISTS fk_employee_id;

-- Drop existing table and recreate with UUID
-- Note: In production with data, you'd need a more complex migration
DROP TABLE IF EXISTS employees;

-- Recreate employees table with UUID
CREATE TABLE employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    secondary_emails JSONB DEFAULT '[]'::jsonb,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Recreate indexes
CREATE UNIQUE INDEX idx_tenant_email ON employees(tenant_id, email);
CREATE INDEX idx_tenant_id ON employees(tenant_id);
CREATE INDEX idx_created_at ON employees(created_at);

-- Add comments
COMMENT ON TABLE employees IS 'Multi-tenant employee records with UUID primary keys';
COMMENT ON COLUMN employees.id IS 'UUID v4 primary key generated by application';
COMMENT ON COLUMN employees.tenant_id IS 'Tenant identifier from JWT token';
COMMENT ON COLUMN employees.secondary_emails IS 'Array of secondary emails from merged employees';

COMMIT;

