// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: events/v1/employee_events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType represents the type of employee lifecycle event
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_CREATED     EventType = 1
	EventType_EVENT_TYPE_UPDATED     EventType = 2
	EventType_EVENT_TYPE_DELETED     EventType = 3
	EventType_EVENT_TYPE_MERGED      EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_CREATED",
		2: "EVENT_TYPE_UPDATED",
		3: "EVENT_TYPE_DELETED",
		4: "EVENT_TYPE_MERGED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_CREATED":     1,
		"EVENT_TYPE_UPDATED":     2,
		"EVENT_TYPE_DELETED":     3,
		"EVENT_TYPE_MERGED":      4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_v1_employee_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_events_v1_employee_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_events_v1_employee_events_proto_rawDescGZIP(), []int{0}
}

// EmployeeEvent is the base event structure containing common metadata
type EmployeeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique event identifier (UUID v4)
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Type of event that occurred
	EventType EventType `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=events.v1.EventType" json:"event_type,omitempty"`
	// Tenant ID that owns this employee
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Timestamp when the event occurred
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// User ID who triggered this event (from JWT sub claim)
	UserId string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Employee data at the time of the event
	Employee *EmployeeData `protobuf:"bytes,6,opt,name=employee,proto3" json:"employee,omitempty"`
	// Additional metadata for the event
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeEvent) Reset() {
	*x = EmployeeEvent{}
	mi := &file_events_v1_employee_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeEvent) ProtoMessage() {}

func (x *EmployeeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_employee_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeEvent.ProtoReflect.Descriptor instead.
func (*EmployeeEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_employee_events_proto_rawDescGZIP(), []int{0}
}

func (x *EmployeeEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EmployeeEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *EmployeeEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EmployeeEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EmployeeEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EmployeeEvent) GetEmployee() *EmployeeData {
	if x != nil {
		return x.Employee
	}
	return nil
}

func (x *EmployeeEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// EmployeeData contains the employee information
type EmployeeData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Employee ID (UUID v4)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Primary email address
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Secondary email addresses (from merges)
	SecondaryEmails []string `protobuf:"bytes,3,rep,name=secondary_emails,json=secondaryEmails,proto3" json:"secondary_emails,omitempty"`
	// First name
	FirstName string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Last name
	LastName string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// When the employee was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the employee was last updated
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeData) Reset() {
	*x = EmployeeData{}
	mi := &file_events_v1_employee_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeData) ProtoMessage() {}

func (x *EmployeeData) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_employee_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeData.ProtoReflect.Descriptor instead.
func (*EmployeeData) Descriptor() ([]byte, []int) {
	return file_events_v1_employee_events_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmployeeData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmployeeData) GetSecondaryEmails() []string {
	if x != nil {
		return x.SecondaryEmails
	}
	return nil
}

func (x *EmployeeData) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *EmployeeData) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *EmployeeData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EmployeeData) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// EmployeeCreatedEvent is published when a new employee is created
type EmployeeCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *EmployeeEvent         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeCreatedEvent) Reset() {
	*x = EmployeeCreatedEvent{}
	mi := &file_events_v1_employee_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeCreatedEvent) ProtoMessage() {}

func (x *EmployeeCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_employee_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeCreatedEvent.ProtoReflect.Descriptor instead.
func (*EmployeeCreatedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_employee_events_proto_rawDescGZIP(), []int{2}
}

func (x *EmployeeCreatedEvent) GetEvent() *EmployeeEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// EmployeeUpdatedEvent is published when an employee is updated
type EmployeeUpdatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Event *EmployeeEvent         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// List of field names that were updated (for tracking changes)
	UpdatedFields []string `protobuf:"bytes,2,rep,name=updated_fields,json=updatedFields,proto3" json:"updated_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeUpdatedEvent) Reset() {
	*x = EmployeeUpdatedEvent{}
	mi := &file_events_v1_employee_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeUpdatedEvent) ProtoMessage() {}

func (x *EmployeeUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_employee_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeUpdatedEvent.ProtoReflect.Descriptor instead.
func (*EmployeeUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_employee_events_proto_rawDescGZIP(), []int{3}
}

func (x *EmployeeUpdatedEvent) GetEvent() *EmployeeEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EmployeeUpdatedEvent) GetUpdatedFields() []string {
	if x != nil {
		return x.UpdatedFields
	}
	return nil
}

// EmployeeDeletedEvent is published when an employee is deleted
type EmployeeDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *EmployeeEvent         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeDeletedEvent) Reset() {
	*x = EmployeeDeletedEvent{}
	mi := &file_events_v1_employee_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeDeletedEvent) ProtoMessage() {}

func (x *EmployeeDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_employee_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeDeletedEvent.ProtoReflect.Descriptor instead.
func (*EmployeeDeletedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_employee_events_proto_rawDescGZIP(), []int{4}
}

func (x *EmployeeDeletedEvent) GetEvent() *EmployeeEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// EmployeeMergedEvent is published when two employees are merged
type EmployeeMergedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Event *EmployeeEvent         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// The email address of the employee that was merged (became secondary)
	MergedFromEmail string `protobuf:"bytes,2,opt,name=merged_from_email,json=mergedFromEmail,proto3" json:"merged_from_email,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EmployeeMergedEvent) Reset() {
	*x = EmployeeMergedEvent{}
	mi := &file_events_v1_employee_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeMergedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeMergedEvent) ProtoMessage() {}

func (x *EmployeeMergedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_employee_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeMergedEvent.ProtoReflect.Descriptor instead.
func (*EmployeeMergedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_employee_events_proto_rawDescGZIP(), []int{5}
}

func (x *EmployeeMergedEvent) GetEvent() *EmployeeEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EmployeeMergedEvent) GetMergedFromEmail() string {
	if x != nil {
		return x.MergedFromEmail
	}
	return ""
}

var File_events_v1_employee_events_proto protoreflect.FileDescriptor

const file_events_v1_employee_events_proto_rawDesc = "" +
	"\n" +
	"\x1fevents/v1/employee_events.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x03\n" +
	"\rEmployeeEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x123\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x14.events.v1.EventTypeR\teventType\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x123\n" +
	"\bemployee\x18\x06 \x01(\v2\x17.events.v1.EmployeeDataR\bemployee\x12B\n" +
	"\bmetadata\x18\a \x03(\v2&.events.v1.EmployeeEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x02\n" +
	"\fEmployeeData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12)\n" +
	"\x10secondary_emails\x18\x03 \x03(\tR\x0fsecondaryEmails\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"F\n" +
	"\x14EmployeeCreatedEvent\x12.\n" +
	"\x05event\x18\x01 \x01(\v2\x18.events.v1.EmployeeEventR\x05event\"m\n" +
	"\x14EmployeeUpdatedEvent\x12.\n" +
	"\x05event\x18\x01 \x01(\v2\x18.events.v1.EmployeeEventR\x05event\x12%\n" +
	"\x0eupdated_fields\x18\x02 \x03(\tR\rupdatedFields\"F\n" +
	"\x14EmployeeDeletedEvent\x12.\n" +
	"\x05event\x18\x01 \x01(\v2\x18.events.v1.EmployeeEventR\x05event\"q\n" +
	"\x13EmployeeMergedEvent\x12.\n" +
	"\x05event\x18\x01 \x01(\v2\x18.events.v1.EmployeeEventR\x05event\x12*\n" +
	"\x11merged_from_email\x18\x02 \x01(\tR\x0fmergedFromEmail*\x86\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_CREATED\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_UPDATED\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_DELETED\x10\x03\x12\x15\n" +
	"\x11EVENT_TYPE_MERGED\x10\x04B?\n" +
	"\x18dev.kratos.api.events.v1P\x01Z!employee-service/api/events/v1;v1b\x06proto3"

var (
	file_events_v1_employee_events_proto_rawDescOnce sync.Once
	file_events_v1_employee_events_proto_rawDescData []byte
)

func file_events_v1_employee_events_proto_rawDescGZIP() []byte {
	file_events_v1_employee_events_proto_rawDescOnce.Do(func() {
		file_events_v1_employee_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_employee_events_proto_rawDesc), len(file_events_v1_employee_events_proto_rawDesc)))
	})
	return file_events_v1_employee_events_proto_rawDescData
}

var file_events_v1_employee_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_v1_employee_events_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_events_v1_employee_events_proto_goTypes = []any{
	(EventType)(0),                // 0: events.v1.EventType
	(*EmployeeEvent)(nil),         // 1: events.v1.EmployeeEvent
	(*EmployeeData)(nil),          // 2: events.v1.EmployeeData
	(*EmployeeCreatedEvent)(nil),  // 3: events.v1.EmployeeCreatedEvent
	(*EmployeeUpdatedEvent)(nil),  // 4: events.v1.EmployeeUpdatedEvent
	(*EmployeeDeletedEvent)(nil),  // 5: events.v1.EmployeeDeletedEvent
	(*EmployeeMergedEvent)(nil),   // 6: events.v1.EmployeeMergedEvent
	nil,                           // 7: events.v1.EmployeeEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_events_v1_employee_events_proto_depIdxs = []int32{
	0,  // 0: events.v1.EmployeeEvent.event_type:type_name -> events.v1.EventType
	8,  // 1: events.v1.EmployeeEvent.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 2: events.v1.EmployeeEvent.employee:type_name -> events.v1.EmployeeData
	7,  // 3: events.v1.EmployeeEvent.metadata:type_name -> events.v1.EmployeeEvent.MetadataEntry
	8,  // 4: events.v1.EmployeeData.created_at:type_name -> google.protobuf.Timestamp
	8,  // 5: events.v1.EmployeeData.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: events.v1.EmployeeCreatedEvent.event:type_name -> events.v1.EmployeeEvent
	1,  // 7: events.v1.EmployeeUpdatedEvent.event:type_name -> events.v1.EmployeeEvent
	1,  // 8: events.v1.EmployeeDeletedEvent.event:type_name -> events.v1.EmployeeEvent
	1,  // 9: events.v1.EmployeeMergedEvent.event:type_name -> events.v1.EmployeeEvent
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_events_v1_employee_events_proto_init() }
func file_events_v1_employee_events_proto_init() {
	if File_events_v1_employee_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_employee_events_proto_rawDesc), len(file_events_v1_employee_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_employee_events_proto_goTypes,
		DependencyIndexes: file_events_v1_employee_events_proto_depIdxs,
		EnumInfos:         file_events_v1_employee_events_proto_enumTypes,
		MessageInfos:      file_events_v1_employee_events_proto_msgTypes,
	}.Build()
	File_events_v1_employee_events_proto = out.File
	file_events_v1_employee_events_proto_goTypes = nil
	file_events_v1_employee_events_proto_depIdxs = nil
}
