// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: events/v1/employee_events.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EmployeeEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EmployeeEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EmployeeEvent with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EmployeeEventMultiError, or
// nil if none found.
func (m *EmployeeEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *EmployeeEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for EventType

	// no validation rules for TenantId

	if all {
		switch v := interface{}(m.GetTimestamp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EmployeeEventValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EmployeeEventValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EmployeeEventValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetEmployee()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EmployeeEventValidationError{
					field:  "Employee",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EmployeeEventValidationError{
					field:  "Employee",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEmployee()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EmployeeEventValidationError{
				field:  "Employee",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Metadata

	if len(errors) > 0 {
		return EmployeeEventMultiError(errors)
	}

	return nil
}

// EmployeeEventMultiError is an error wrapping multiple validation errors
// returned by EmployeeEvent.ValidateAll() if the designated constraints
// aren't met.
type EmployeeEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmployeeEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmployeeEventMultiError) AllErrors() []error { return m }

// EmployeeEventValidationError is the validation error returned by
// EmployeeEvent.Validate if the designated constraints aren't met.
type EmployeeEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmployeeEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmployeeEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmployeeEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmployeeEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmployeeEventValidationError) ErrorName() string { return "EmployeeEventValidationError" }

// Error satisfies the builtin error interface
func (e EmployeeEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmployeeEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmployeeEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmployeeEventValidationError{}

// Validate checks the field values on EmployeeData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EmployeeData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EmployeeData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EmployeeDataMultiError, or
// nil if none found.
func (m *EmployeeData) ValidateAll() error {
	return m.validate(true)
}

func (m *EmployeeData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Email

	// no validation rules for FirstName

	// no validation rules for LastName

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EmployeeDataValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EmployeeDataValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EmployeeDataValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EmployeeDataValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EmployeeDataValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EmployeeDataValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return EmployeeDataMultiError(errors)
	}

	return nil
}

// EmployeeDataMultiError is an error wrapping multiple validation errors
// returned by EmployeeData.ValidateAll() if the designated constraints aren't met.
type EmployeeDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmployeeDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmployeeDataMultiError) AllErrors() []error { return m }

// EmployeeDataValidationError is the validation error returned by
// EmployeeData.Validate if the designated constraints aren't met.
type EmployeeDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmployeeDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmployeeDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmployeeDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmployeeDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmployeeDataValidationError) ErrorName() string { return "EmployeeDataValidationError" }

// Error satisfies the builtin error interface
func (e EmployeeDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmployeeData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmployeeDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmployeeDataValidationError{}

// Validate checks the field values on EmployeeCreatedEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EmployeeCreatedEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EmployeeCreatedEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EmployeeCreatedEventMultiError, or nil if none found.
func (m *EmployeeCreatedEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *EmployeeCreatedEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEvent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EmployeeCreatedEventValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EmployeeCreatedEventValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEvent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EmployeeCreatedEventValidationError{
				field:  "Event",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return EmployeeCreatedEventMultiError(errors)
	}

	return nil
}

// EmployeeCreatedEventMultiError is an error wrapping multiple validation
// errors returned by EmployeeCreatedEvent.ValidateAll() if the designated
// constraints aren't met.
type EmployeeCreatedEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmployeeCreatedEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmployeeCreatedEventMultiError) AllErrors() []error { return m }

// EmployeeCreatedEventValidationError is the validation error returned by
// EmployeeCreatedEvent.Validate if the designated constraints aren't met.
type EmployeeCreatedEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmployeeCreatedEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmployeeCreatedEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmployeeCreatedEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmployeeCreatedEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmployeeCreatedEventValidationError) ErrorName() string {
	return "EmployeeCreatedEventValidationError"
}

// Error satisfies the builtin error interface
func (e EmployeeCreatedEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmployeeCreatedEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmployeeCreatedEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmployeeCreatedEventValidationError{}

// Validate checks the field values on EmployeeUpdatedEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EmployeeUpdatedEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EmployeeUpdatedEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EmployeeUpdatedEventMultiError, or nil if none found.
func (m *EmployeeUpdatedEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *EmployeeUpdatedEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEvent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EmployeeUpdatedEventValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EmployeeUpdatedEventValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEvent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EmployeeUpdatedEventValidationError{
				field:  "Event",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return EmployeeUpdatedEventMultiError(errors)
	}

	return nil
}

// EmployeeUpdatedEventMultiError is an error wrapping multiple validation
// errors returned by EmployeeUpdatedEvent.ValidateAll() if the designated
// constraints aren't met.
type EmployeeUpdatedEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmployeeUpdatedEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmployeeUpdatedEventMultiError) AllErrors() []error { return m }

// EmployeeUpdatedEventValidationError is the validation error returned by
// EmployeeUpdatedEvent.Validate if the designated constraints aren't met.
type EmployeeUpdatedEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmployeeUpdatedEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmployeeUpdatedEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmployeeUpdatedEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmployeeUpdatedEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmployeeUpdatedEventValidationError) ErrorName() string {
	return "EmployeeUpdatedEventValidationError"
}

// Error satisfies the builtin error interface
func (e EmployeeUpdatedEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmployeeUpdatedEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmployeeUpdatedEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmployeeUpdatedEventValidationError{}

// Validate checks the field values on EmployeeDeletedEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EmployeeDeletedEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EmployeeDeletedEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EmployeeDeletedEventMultiError, or nil if none found.
func (m *EmployeeDeletedEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *EmployeeDeletedEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEvent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EmployeeDeletedEventValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EmployeeDeletedEventValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEvent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EmployeeDeletedEventValidationError{
				field:  "Event",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return EmployeeDeletedEventMultiError(errors)
	}

	return nil
}

// EmployeeDeletedEventMultiError is an error wrapping multiple validation
// errors returned by EmployeeDeletedEvent.ValidateAll() if the designated
// constraints aren't met.
type EmployeeDeletedEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmployeeDeletedEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmployeeDeletedEventMultiError) AllErrors() []error { return m }

// EmployeeDeletedEventValidationError is the validation error returned by
// EmployeeDeletedEvent.Validate if the designated constraints aren't met.
type EmployeeDeletedEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmployeeDeletedEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmployeeDeletedEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmployeeDeletedEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmployeeDeletedEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmployeeDeletedEventValidationError) ErrorName() string {
	return "EmployeeDeletedEventValidationError"
}

// Error satisfies the builtin error interface
func (e EmployeeDeletedEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmployeeDeletedEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmployeeDeletedEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmployeeDeletedEventValidationError{}

// Validate checks the field values on EmployeeMergedEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EmployeeMergedEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EmployeeMergedEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EmployeeMergedEventMultiError, or nil if none found.
func (m *EmployeeMergedEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *EmployeeMergedEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEvent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EmployeeMergedEventValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EmployeeMergedEventValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEvent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EmployeeMergedEventValidationError{
				field:  "Event",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for MergedFromEmail

	if len(errors) > 0 {
		return EmployeeMergedEventMultiError(errors)
	}

	return nil
}

// EmployeeMergedEventMultiError is an error wrapping multiple validation
// errors returned by EmployeeMergedEvent.ValidateAll() if the designated
// constraints aren't met.
type EmployeeMergedEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmployeeMergedEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmployeeMergedEventMultiError) AllErrors() []error { return m }

// EmployeeMergedEventValidationError is the validation error returned by
// EmployeeMergedEvent.Validate if the designated constraints aren't met.
type EmployeeMergedEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmployeeMergedEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmployeeMergedEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmployeeMergedEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmployeeMergedEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmployeeMergedEventValidationError) ErrorName() string {
	return "EmployeeMergedEventValidationError"
}

// Error satisfies the builtin error interface
func (e EmployeeMergedEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmployeeMergedEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmployeeMergedEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmployeeMergedEventValidationError{}
