// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.3
// source: employee/v1/employee.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEmployeeServiceCreateEmployee = "/employee.v1.EmployeeService/CreateEmployee"
const OperationEmployeeServiceDeleteEmployee = "/employee.v1.EmployeeService/DeleteEmployee"
const OperationEmployeeServiceGetEmployee = "/employee.v1.EmployeeService/GetEmployee"
const OperationEmployeeServiceGetEmployeeByEmail = "/employee.v1.EmployeeService/GetEmployeeByEmail"
const OperationEmployeeServiceListEmployees = "/employee.v1.EmployeeService/ListEmployees"
const OperationEmployeeServiceMergeEmployees = "/employee.v1.EmployeeService/MergeEmployees"
const OperationEmployeeServiceUpdateEmployee = "/employee.v1.EmployeeService/UpdateEmployee"

type EmployeeServiceHTTPServer interface {
	// CreateEmployee Creates a new employee
	CreateEmployee(context.Context, *CreateEmployeeRequest) (*CreateEmployeeResponse, error)
	// DeleteEmployee Deletes an employee
	DeleteEmployee(context.Context, *DeleteEmployeeRequest) (*DeleteEmployeeResponse, error)
	// GetEmployee Gets an employee by ID
	GetEmployee(context.Context, *GetEmployeeRequest) (*GetEmployeeResponse, error)
	// GetEmployeeByEmail Gets an employee by email (deprecated - use ListEmployees with email param)
	GetEmployeeByEmail(context.Context, *GetEmployeeByEmailRequest) (*GetEmployeeByEmailResponse, error)
	// ListEmployees Lists employees with pagination and filtering
	// Use query parameters: ?page=1&page_size=20&email=...
	ListEmployees(context.Context, *ListEmployeesRequest) (*ListEmployeesResponse, error)
	// MergeEmployees Merges two employees by email
	MergeEmployees(context.Context, *MergeEmployeesRequest) (*MergeEmployeesResponse, error)
	// UpdateEmployee Updates an existing employee
	UpdateEmployee(context.Context, *UpdateEmployeeRequest) (*UpdateEmployeeResponse, error)
}

func RegisterEmployeeServiceHTTPServer(s *http.Server, srv EmployeeServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/employees", _EmployeeService_CreateEmployee0_HTTP_Handler(srv))
	r.PUT("/api/v1/employees/{id}", _EmployeeService_UpdateEmployee0_HTTP_Handler(srv))
	r.DELETE("/api/v1/employees/{id}", _EmployeeService_DeleteEmployee0_HTTP_Handler(srv))
	r.GET("/api/v1/employees", _EmployeeService_ListEmployees0_HTTP_Handler(srv))
	r.GET("/api/v1/employees/{id}", _EmployeeService_GetEmployee0_HTTP_Handler(srv))
	r.GET("/api/v1/employees:byEmail", _EmployeeService_GetEmployeeByEmail0_HTTP_Handler(srv))
	r.POST("/api/v1/employees/merge", _EmployeeService_MergeEmployees0_HTTP_Handler(srv))
}

func _EmployeeService_CreateEmployee0_HTTP_Handler(srv EmployeeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEmployeeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployeeServiceCreateEmployee)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEmployee(ctx, req.(*CreateEmployeeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateEmployeeResponse)
		return ctx.Result(200, reply)
	}
}

func _EmployeeService_UpdateEmployee0_HTTP_Handler(srv EmployeeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEmployeeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployeeServiceUpdateEmployee)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEmployee(ctx, req.(*UpdateEmployeeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateEmployeeResponse)
		return ctx.Result(200, reply)
	}
}

func _EmployeeService_DeleteEmployee0_HTTP_Handler(srv EmployeeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEmployeeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployeeServiceDeleteEmployee)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteEmployee(ctx, req.(*DeleteEmployeeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteEmployeeResponse)
		return ctx.Result(200, reply)
	}
}

func _EmployeeService_ListEmployees0_HTTP_Handler(srv EmployeeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEmployeesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployeeServiceListEmployees)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEmployees(ctx, req.(*ListEmployeesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEmployeesResponse)
		return ctx.Result(200, reply)
	}
}

func _EmployeeService_GetEmployee0_HTTP_Handler(srv EmployeeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEmployeeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployeeServiceGetEmployee)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmployee(ctx, req.(*GetEmployeeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEmployeeResponse)
		return ctx.Result(200, reply)
	}
}

func _EmployeeService_GetEmployeeByEmail0_HTTP_Handler(srv EmployeeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEmployeeByEmailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployeeServiceGetEmployeeByEmail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmployeeByEmail(ctx, req.(*GetEmployeeByEmailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEmployeeByEmailResponse)
		return ctx.Result(200, reply)
	}
}

func _EmployeeService_MergeEmployees0_HTTP_Handler(srv EmployeeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MergeEmployeesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployeeServiceMergeEmployees)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MergeEmployees(ctx, req.(*MergeEmployeesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MergeEmployeesResponse)
		return ctx.Result(200, reply)
	}
}

type EmployeeServiceHTTPClient interface {
	// CreateEmployee Creates a new employee
	CreateEmployee(ctx context.Context, req *CreateEmployeeRequest, opts ...http.CallOption) (rsp *CreateEmployeeResponse, err error)
	// DeleteEmployee Deletes an employee
	DeleteEmployee(ctx context.Context, req *DeleteEmployeeRequest, opts ...http.CallOption) (rsp *DeleteEmployeeResponse, err error)
	// GetEmployee Gets an employee by ID
	GetEmployee(ctx context.Context, req *GetEmployeeRequest, opts ...http.CallOption) (rsp *GetEmployeeResponse, err error)
	// GetEmployeeByEmail Gets an employee by email (deprecated - use ListEmployees with email param)
	GetEmployeeByEmail(ctx context.Context, req *GetEmployeeByEmailRequest, opts ...http.CallOption) (rsp *GetEmployeeByEmailResponse, err error)
	// ListEmployees Lists employees with pagination and filtering
	// Use query parameters: ?page=1&page_size=20&email=...
	ListEmployees(ctx context.Context, req *ListEmployeesRequest, opts ...http.CallOption) (rsp *ListEmployeesResponse, err error)
	// MergeEmployees Merges two employees by email
	MergeEmployees(ctx context.Context, req *MergeEmployeesRequest, opts ...http.CallOption) (rsp *MergeEmployeesResponse, err error)
	// UpdateEmployee Updates an existing employee
	UpdateEmployee(ctx context.Context, req *UpdateEmployeeRequest, opts ...http.CallOption) (rsp *UpdateEmployeeResponse, err error)
}

type EmployeeServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewEmployeeServiceHTTPClient(client *http.Client) EmployeeServiceHTTPClient {
	return &EmployeeServiceHTTPClientImpl{client}
}

// CreateEmployee Creates a new employee
func (c *EmployeeServiceHTTPClientImpl) CreateEmployee(ctx context.Context, in *CreateEmployeeRequest, opts ...http.CallOption) (*CreateEmployeeResponse, error) {
	var out CreateEmployeeResponse
	pattern := "/api/v1/employees"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEmployeeServiceCreateEmployee))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteEmployee Deletes an employee
func (c *EmployeeServiceHTTPClientImpl) DeleteEmployee(ctx context.Context, in *DeleteEmployeeRequest, opts ...http.CallOption) (*DeleteEmployeeResponse, error) {
	var out DeleteEmployeeResponse
	pattern := "/api/v1/employees/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployeeServiceDeleteEmployee))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetEmployee Gets an employee by ID
func (c *EmployeeServiceHTTPClientImpl) GetEmployee(ctx context.Context, in *GetEmployeeRequest, opts ...http.CallOption) (*GetEmployeeResponse, error) {
	var out GetEmployeeResponse
	pattern := "/api/v1/employees/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployeeServiceGetEmployee))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetEmployeeByEmail Gets an employee by email (deprecated - use ListEmployees with email param)
func (c *EmployeeServiceHTTPClientImpl) GetEmployeeByEmail(ctx context.Context, in *GetEmployeeByEmailRequest, opts ...http.CallOption) (*GetEmployeeByEmailResponse, error) {
	var out GetEmployeeByEmailResponse
	pattern := "/api/v1/employees:byEmail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployeeServiceGetEmployeeByEmail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListEmployees Lists employees with pagination and filtering
// Use query parameters: ?page=1&page_size=20&email=...
func (c *EmployeeServiceHTTPClientImpl) ListEmployees(ctx context.Context, in *ListEmployeesRequest, opts ...http.CallOption) (*ListEmployeesResponse, error) {
	var out ListEmployeesResponse
	pattern := "/api/v1/employees"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployeeServiceListEmployees))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MergeEmployees Merges two employees by email
func (c *EmployeeServiceHTTPClientImpl) MergeEmployees(ctx context.Context, in *MergeEmployeesRequest, opts ...http.CallOption) (*MergeEmployeesResponse, error) {
	var out MergeEmployeesResponse
	pattern := "/api/v1/employees/merge"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEmployeeServiceMergeEmployees))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateEmployee Updates an existing employee
func (c *EmployeeServiceHTTPClientImpl) UpdateEmployee(ctx context.Context, in *UpdateEmployeeRequest, opts ...http.CallOption) (*UpdateEmployeeResponse, error) {
	var out UpdateEmployeeResponse
	pattern := "/api/v1/employees/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEmployeeServiceUpdateEmployee))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
