// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: employee/v1/employee.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Employee message - tenant_id is NOT exposed, it's managed internally
type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // UUID v4 as string
	Emails        []string               `protobuf:"bytes,2,rep,name=emails,proto3" json:"emails,omitempty"` // All email addresses for this employee
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_employee_v1_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Employee) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *Employee) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Employee) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Employee) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Employee) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Create Employee
type CreateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []string               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeRequest) Reset() {
	*x = CreateEmployeeRequest{}
	mi := &file_employee_v1_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeRequest) ProtoMessage() {}

func (x *CreateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEmployeeRequest) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *CreateEmployeeRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateEmployeeRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type CreateEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeResponse) Reset() {
	*x = CreateEmployeeResponse{}
	mi := &file_employee_v1_employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeResponse) ProtoMessage() {}

func (x *CreateEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeResponse.ProtoReflect.Descriptor instead.
func (*CreateEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

// Update Employee
type UpdateEmployeeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional fields - only validated if set
	Emails        []string `protobuf:"bytes,2,rep,name=emails,proto3" json:"emails,omitempty"`
	FirstName     *string  `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string  `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeRequest) Reset() {
	*x = UpdateEmployeeRequest{}
	mi := &file_employee_v1_employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeRequest) ProtoMessage() {}

func (x *UpdateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEmployeeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *UpdateEmployeeRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

type UpdateEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeResponse) Reset() {
	*x = UpdateEmployeeResponse{}
	mi := &file_employee_v1_employee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeResponse) ProtoMessage() {}

func (x *UpdateEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

// Delete Employee
type DeleteEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeRequest) Reset() {
	*x = DeleteEmployeeRequest{}
	mi := &file_employee_v1_employee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeRequest) ProtoMessage() {}

func (x *DeleteEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEmployeeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeResponse) Reset() {
	*x = DeleteEmployeeResponse{}
	mi := &file_employee_v1_employee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeResponse) ProtoMessage() {}

func (x *DeleteEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeResponse.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEmployeeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get Employee by ID
type GetEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeRequest) Reset() {
	*x = GetEmployeeRequest{}
	mi := &file_employee_v1_employee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeRequest) ProtoMessage() {}

func (x *GetEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{7}
}

func (x *GetEmployeeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeResponse) Reset() {
	*x = GetEmployeeResponse{}
	mi := &file_employee_v1_employee_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeResponse) ProtoMessage() {}

func (x *GetEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{8}
}

func (x *GetEmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

// Get Employee by Email
type GetEmployeeByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByEmailRequest) Reset() {
	*x = GetEmployeeByEmailRequest{}
	mi := &file_employee_v1_employee_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByEmailRequest) ProtoMessage() {}

func (x *GetEmployeeByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeByEmailRequest) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{9}
}

func (x *GetEmployeeByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetEmployeeByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByEmailResponse) Reset() {
	*x = GetEmployeeByEmailResponse{}
	mi := &file_employee_v1_employee_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByEmailResponse) ProtoMessage() {}

func (x *GetEmployeeByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByEmailResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeByEmailResponse) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{10}
}

func (x *GetEmployeeByEmailResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

// List Employees
type ListEmployeesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// page defaults to 1 if 0 or not set (handled in business logic)
	Page *int32 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	// page_size defaults to 20 if 0 or not set (handled in business logic)
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	CreatedAfter  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_after,json=createdAfter,proto3" json:"created_after,omitempty"`
	CreatedBefore *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_before,json=createdBefore,proto3" json:"created_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmployeesRequest) Reset() {
	*x = ListEmployeesRequest{}
	mi := &file_employee_v1_employee_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmployeesRequest) ProtoMessage() {}

func (x *ListEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmployeesRequest.ProtoReflect.Descriptor instead.
func (*ListEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{11}
}

func (x *ListEmployeesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListEmployeesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListEmployeesRequest) GetCreatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAfter
	}
	return nil
}

func (x *ListEmployeesRequest) GetCreatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedBefore
	}
	return nil
}

type ListEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmployeesResponse) Reset() {
	*x = ListEmployeesResponse{}
	mi := &file_employee_v1_employee_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmployeesResponse) ProtoMessage() {}

func (x *ListEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmployeesResponse.ProtoReflect.Descriptor instead.
func (*ListEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{12}
}

func (x *ListEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *ListEmployeesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListEmployeesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEmployeesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Merge Employees
type MergeEmployeesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrimaryEmail   string                 `protobuf:"bytes,1,opt,name=primary_email,json=primaryEmail,proto3" json:"primary_email,omitempty"`
	SecondaryEmail string                 `protobuf:"bytes,2,opt,name=secondary_email,json=secondaryEmail,proto3" json:"secondary_email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MergeEmployeesRequest) Reset() {
	*x = MergeEmployeesRequest{}
	mi := &file_employee_v1_employee_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeEmployeesRequest) ProtoMessage() {}

func (x *MergeEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeEmployeesRequest.ProtoReflect.Descriptor instead.
func (*MergeEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{13}
}

func (x *MergeEmployeesRequest) GetPrimaryEmail() string {
	if x != nil {
		return x.PrimaryEmail
	}
	return ""
}

func (x *MergeEmployeesRequest) GetSecondaryEmail() string {
	if x != nil {
		return x.SecondaryEmail
	}
	return ""
}

type MergeEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeEmployeesResponse) Reset() {
	*x = MergeEmployeesResponse{}
	mi := &file_employee_v1_employee_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeEmployeesResponse) ProtoMessage() {}

func (x *MergeEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_v1_employee_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeEmployeesResponse.ProtoReflect.Descriptor instead.
func (*MergeEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_employee_v1_employee_proto_rawDescGZIP(), []int{14}
}

func (x *MergeEmployeesResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

var File_employee_v1_employee_proto protoreflect.FileDescriptor

const file_employee_v1_employee_proto_rawDesc = "" +
	"\n" +
	"\x1aemployee/v1/employee.proto\x12\vemployee.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xe4\x01\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06emails\x18\x02 \x03(\tR\x06emails\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbc\x01\n" +
	"\x15CreateEmployeeRequest\x12-\n" +
	"\x06emails\x18\x01 \x03(\tB\x15\xbaH\x12\x92\x01\x0f\b\x01\x10\n" +
	"\"\tr\a\x10\x03\x18\xff\x01`\x01R\x06emails\x12:\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tB\x1b\xbaH\x18r\x16\x10\x01\x18d2\x10^[a-zA-Z\\s\\-']+$R\tfirstName\x128\n" +
	"\tlast_name\x18\x03 \x01(\tB\x1b\xbaH\x18r\x16\x10\x01\x18d2\x10^[a-zA-Z\\s\\-']+$R\blastName\"K\n" +
	"\x16CreateEmployeeResponse\x121\n" +
	"\bemployee\x18\x01 \x01(\v2\x15.employee.v1.EmployeeR\bemployee\"\xfb\x01\n" +
	"\x15UpdateEmployeeRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12+\n" +
	"\x06emails\x18\x02 \x03(\tB\x13\xbaH\x10\x92\x01\r\x10\n" +
	"\"\tr\a\x10\x03\x18\xff\x01`\x01R\x06emails\x12?\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tB\x1b\xbaH\x18r\x16\x10\x01\x18d2\x10^[a-zA-Z\\s\\-']+$H\x00R\tfirstName\x88\x01\x01\x12=\n" +
	"\tlast_name\x18\x04 \x01(\tB\x1b\xbaH\x18r\x16\x10\x01\x18d2\x10^[a-zA-Z\\s\\-']+$H\x01R\blastName\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name\"K\n" +
	"\x16UpdateEmployeeResponse\x121\n" +
	"\bemployee\x18\x01 \x01(\v2\x15.employee.v1.EmployeeR\bemployee\"1\n" +
	"\x15DeleteEmployeeRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"2\n" +
	"\x16DeleteEmployeeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x12GetEmployeeRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"H\n" +
	"\x13GetEmployeeResponse\x121\n" +
	"\bemployee\x18\x01 \x01(\v2\x15.employee.v1.EmployeeR\bemployee\"1\n" +
	"\x19GetEmployeeByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"O\n" +
	"\x1aGetEmployeeByEmailResponse\x121\n" +
	"\bemployee\x18\x01 \x01(\v2\x15.employee.v1.EmployeeR\bemployee\"\xff\x01\n" +
	"\x14ListEmployeesRequest\x12!\n" +
	"\x04page\x18\x01 \x01(\x05B\b\xbaH\x05\x1a\x03\x18\x90NH\x00R\x04page\x88\x01\x01\x12)\n" +
	"\tpage_size\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02\x18dH\x01R\bpageSize\x88\x01\x01\x12?\n" +
	"\rcreated_after\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAfter\x12A\n" +
	"\x0ecreated_before\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rcreatedBeforeB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"\x93\x01\n" +
	"\x15ListEmployeesResponse\x123\n" +
	"\temployees\x18\x01 \x03(\v2\x15.employee.v1.EmployeeR\temployees\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x81\x01\n" +
	"\x15MergeEmployeesRequest\x121\n" +
	"\rprimary_email\x18\x01 \x01(\tB\f\xbaH\tr\a\x10\x03\x18\xff\x01`\x01R\fprimaryEmail\x125\n" +
	"\x0fsecondary_email\x18\x02 \x01(\tB\f\xbaH\tr\a\x10\x03\x18\xff\x01`\x01R\x0esecondaryEmail\"K\n" +
	"\x16MergeEmployeesResponse\x121\n" +
	"\bemployee\x18\x01 \x01(\v2\x15.employee.v1.EmployeeR\bemployee2\xf2\x06\n" +
	"\x0fEmployeeService\x12w\n" +
	"\x0eCreateEmployee\x12\".employee.v1.CreateEmployeeRequest\x1a#.employee.v1.CreateEmployeeResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/employees\x12|\n" +
	"\x0eUpdateEmployee\x12\".employee.v1.UpdateEmployeeRequest\x1a#.employee.v1.UpdateEmployeeResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/v1/employees/{id}\x12y\n" +
	"\x0eDeleteEmployee\x12\".employee.v1.DeleteEmployeeRequest\x1a#.employee.v1.DeleteEmployeeResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/employees/{id}\x12q\n" +
	"\rListEmployees\x12!.employee.v1.ListEmployeesRequest\x1a\".employee.v1.ListEmployeesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/employees\x12p\n" +
	"\vGetEmployee\x12\x1f.employee.v1.GetEmployeeRequest\x1a .employee.v1.GetEmployeeResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/employees/{id}\x12\x88\x01\n" +
	"\x12GetEmployeeByEmail\x12&.employee.v1.GetEmployeeByEmailRequest\x1a'.employee.v1.GetEmployeeByEmailResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/employees:byEmail\x12}\n" +
	"\x0eMergeEmployees\x12\".employee.v1.MergeEmployeesRequest\x1a#.employee.v1.MergeEmployeesResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/employees/mergeBT\n" +
	"\x1adev.kratos.api.employee.v1B\x0fEmployeeProtoV1P\x01Z#employee-service/api/employee/v1;v1b\x06proto3"

var (
	file_employee_v1_employee_proto_rawDescOnce sync.Once
	file_employee_v1_employee_proto_rawDescData []byte
)

func file_employee_v1_employee_proto_rawDescGZIP() []byte {
	file_employee_v1_employee_proto_rawDescOnce.Do(func() {
		file_employee_v1_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_v1_employee_proto_rawDesc), len(file_employee_v1_employee_proto_rawDesc)))
	})
	return file_employee_v1_employee_proto_rawDescData
}

var file_employee_v1_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_employee_v1_employee_proto_goTypes = []any{
	(*Employee)(nil),                   // 0: employee.v1.Employee
	(*CreateEmployeeRequest)(nil),      // 1: employee.v1.CreateEmployeeRequest
	(*CreateEmployeeResponse)(nil),     // 2: employee.v1.CreateEmployeeResponse
	(*UpdateEmployeeRequest)(nil),      // 3: employee.v1.UpdateEmployeeRequest
	(*UpdateEmployeeResponse)(nil),     // 4: employee.v1.UpdateEmployeeResponse
	(*DeleteEmployeeRequest)(nil),      // 5: employee.v1.DeleteEmployeeRequest
	(*DeleteEmployeeResponse)(nil),     // 6: employee.v1.DeleteEmployeeResponse
	(*GetEmployeeRequest)(nil),         // 7: employee.v1.GetEmployeeRequest
	(*GetEmployeeResponse)(nil),        // 8: employee.v1.GetEmployeeResponse
	(*GetEmployeeByEmailRequest)(nil),  // 9: employee.v1.GetEmployeeByEmailRequest
	(*GetEmployeeByEmailResponse)(nil), // 10: employee.v1.GetEmployeeByEmailResponse
	(*ListEmployeesRequest)(nil),       // 11: employee.v1.ListEmployeesRequest
	(*ListEmployeesResponse)(nil),      // 12: employee.v1.ListEmployeesResponse
	(*MergeEmployeesRequest)(nil),      // 13: employee.v1.MergeEmployeesRequest
	(*MergeEmployeesResponse)(nil),     // 14: employee.v1.MergeEmployeesResponse
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
}
var file_employee_v1_employee_proto_depIdxs = []int32{
	15, // 0: employee.v1.Employee.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: employee.v1.Employee.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: employee.v1.CreateEmployeeResponse.employee:type_name -> employee.v1.Employee
	0,  // 3: employee.v1.UpdateEmployeeResponse.employee:type_name -> employee.v1.Employee
	0,  // 4: employee.v1.GetEmployeeResponse.employee:type_name -> employee.v1.Employee
	0,  // 5: employee.v1.GetEmployeeByEmailResponse.employee:type_name -> employee.v1.Employee
	15, // 6: employee.v1.ListEmployeesRequest.created_after:type_name -> google.protobuf.Timestamp
	15, // 7: employee.v1.ListEmployeesRequest.created_before:type_name -> google.protobuf.Timestamp
	0,  // 8: employee.v1.ListEmployeesResponse.employees:type_name -> employee.v1.Employee
	0,  // 9: employee.v1.MergeEmployeesResponse.employee:type_name -> employee.v1.Employee
	1,  // 10: employee.v1.EmployeeService.CreateEmployee:input_type -> employee.v1.CreateEmployeeRequest
	3,  // 11: employee.v1.EmployeeService.UpdateEmployee:input_type -> employee.v1.UpdateEmployeeRequest
	5,  // 12: employee.v1.EmployeeService.DeleteEmployee:input_type -> employee.v1.DeleteEmployeeRequest
	11, // 13: employee.v1.EmployeeService.ListEmployees:input_type -> employee.v1.ListEmployeesRequest
	7,  // 14: employee.v1.EmployeeService.GetEmployee:input_type -> employee.v1.GetEmployeeRequest
	9,  // 15: employee.v1.EmployeeService.GetEmployeeByEmail:input_type -> employee.v1.GetEmployeeByEmailRequest
	13, // 16: employee.v1.EmployeeService.MergeEmployees:input_type -> employee.v1.MergeEmployeesRequest
	2,  // 17: employee.v1.EmployeeService.CreateEmployee:output_type -> employee.v1.CreateEmployeeResponse
	4,  // 18: employee.v1.EmployeeService.UpdateEmployee:output_type -> employee.v1.UpdateEmployeeResponse
	6,  // 19: employee.v1.EmployeeService.DeleteEmployee:output_type -> employee.v1.DeleteEmployeeResponse
	12, // 20: employee.v1.EmployeeService.ListEmployees:output_type -> employee.v1.ListEmployeesResponse
	8,  // 21: employee.v1.EmployeeService.GetEmployee:output_type -> employee.v1.GetEmployeeResponse
	10, // 22: employee.v1.EmployeeService.GetEmployeeByEmail:output_type -> employee.v1.GetEmployeeByEmailResponse
	14, // 23: employee.v1.EmployeeService.MergeEmployees:output_type -> employee.v1.MergeEmployeesResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_employee_v1_employee_proto_init() }
func file_employee_v1_employee_proto_init() {
	if File_employee_v1_employee_proto != nil {
		return
	}
	file_employee_v1_employee_proto_msgTypes[3].OneofWrappers = []any{}
	file_employee_v1_employee_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_v1_employee_proto_rawDesc), len(file_employee_v1_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_v1_employee_proto_goTypes,
		DependencyIndexes: file_employee_v1_employee_proto_depIdxs,
		MessageInfos:      file_employee_v1_employee_proto_msgTypes,
	}.Build()
	File_employee_v1_employee_proto = out.File
	file_employee_v1_employee_proto_goTypes = nil
	file_employee_v1_employee_proto_depIdxs = nil
}
