// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: employee/v1/error_reason.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_UNKNOWN                 ErrorReason = 0
	ErrorReason_EMPLOYEE_NOT_FOUND      ErrorReason = 1
	ErrorReason_EMPLOYEE_ALREADY_EXISTS ErrorReason = 2
	ErrorReason_EMPLOYEE_NOT_IN_TENANT  ErrorReason = 3
	ErrorReason_INVALID_EMAIL           ErrorReason = 4
	ErrorReason_INVALID_EMPLOYEE_ID     ErrorReason = 5
	ErrorReason_TENANT_NOT_FOUND        ErrorReason = 6
	ErrorReason_UNAUTHORIZED            ErrorReason = 7
	ErrorReason_INVALID_UUID            ErrorReason = 8
	ErrorReason_INVALID_DATE_RANGE      ErrorReason = 9
	ErrorReason_INVALID_MERGE           ErrorReason = 10
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "EMPLOYEE_NOT_FOUND",
		2:  "EMPLOYEE_ALREADY_EXISTS",
		3:  "EMPLOYEE_NOT_IN_TENANT",
		4:  "INVALID_EMAIL",
		5:  "INVALID_EMPLOYEE_ID",
		6:  "TENANT_NOT_FOUND",
		7:  "UNAUTHORIZED",
		8:  "INVALID_UUID",
		9:  "INVALID_DATE_RANGE",
		10: "INVALID_MERGE",
	}
	ErrorReason_value = map[string]int32{
		"UNKNOWN":                 0,
		"EMPLOYEE_NOT_FOUND":      1,
		"EMPLOYEE_ALREADY_EXISTS": 2,
		"EMPLOYEE_NOT_IN_TENANT":  3,
		"INVALID_EMAIL":           4,
		"INVALID_EMPLOYEE_ID":     5,
		"TENANT_NOT_FOUND":        6,
		"UNAUTHORIZED":            7,
		"INVALID_UUID":            8,
		"INVALID_DATE_RANGE":      9,
		"INVALID_MERGE":           10,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_employee_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_employee_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_employee_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_employee_v1_error_reason_proto protoreflect.FileDescriptor

const file_employee_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1eemployee/v1/error_reason.proto\x12\vemployee.v1*\xfc\x01\n" +
	"\vErrorReason\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x16\n" +
	"\x12EMPLOYEE_NOT_FOUND\x10\x01\x12\x1b\n" +
	"\x17EMPLOYEE_ALREADY_EXISTS\x10\x02\x12\x1a\n" +
	"\x16EMPLOYEE_NOT_IN_TENANT\x10\x03\x12\x11\n" +
	"\rINVALID_EMAIL\x10\x04\x12\x17\n" +
	"\x13INVALID_EMPLOYEE_ID\x10\x05\x12\x14\n" +
	"\x10TENANT_NOT_FOUND\x10\x06\x12\x10\n" +
	"\fUNAUTHORIZED\x10\a\x12\x10\n" +
	"\fINVALID_UUID\x10\b\x12\x16\n" +
	"\x12INVALID_DATE_RANGE\x10\t\x12\x11\n" +
	"\rINVALID_MERGE\x10\n" +
	"BC\n" +
	"\x1adev.kratos.api.employee.v1P\x01Z#employee-service/api/employee/v1;v1b\x06proto3"

var (
	file_employee_v1_error_reason_proto_rawDescOnce sync.Once
	file_employee_v1_error_reason_proto_rawDescData []byte
)

func file_employee_v1_error_reason_proto_rawDescGZIP() []byte {
	file_employee_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_employee_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_v1_error_reason_proto_rawDesc), len(file_employee_v1_error_reason_proto_rawDesc)))
	})
	return file_employee_v1_error_reason_proto_rawDescData
}

var file_employee_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_employee_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: employee.v1.ErrorReason
}
var file_employee_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_employee_v1_error_reason_proto_init() }
func file_employee_v1_error_reason_proto_init() {
	if File_employee_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_v1_error_reason_proto_rawDesc), len(file_employee_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_employee_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_employee_v1_error_reason_proto_enumTypes,
	}.Build()
	File_employee_v1_error_reason_proto = out.File
	file_employee_v1_error_reason_proto_goTypes = nil
	file_employee_v1_error_reason_proto_depIdxs = nil
}
