// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"employee-service/internal/biz"
	"employee-service/internal/conf"
	"employee-service/internal/data"
	"employee-service/internal/server"
	"employee-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	employeeRepo := data.NewEmployeeRepo(dataData, logger)
	employeeUsecase := biz.NewEmployeeUsecase(employeeRepo, logger)
	employeeService := service.NewEmployeeService(employeeUsecase)
	grpcServer := server.NewGRPCServer(confServer, auth, employeeService, logger)
	httpServer := server.NewHTTPServer(confServer, auth, employeeService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
