// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"employee-service/internal/biz"
	"employee-service/internal/conf"
	"employee-service/internal/data"
	"employee-service/internal/observability"
	"employee-service/internal/server"
	"employee-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(serverConf *conf.Server, dataConf *conf.Data, authConf *conf.Auth, obsConf *conf.Observability, serviceName observability.ServiceName, version observability.ServiceVersion, logger log.Logger) (*kratos.App, func(), error) {
	serviceInfo := observability.NewServiceInfo(serviceName, version)
	observabilityObservability, cleanup, err := observability.NewObservability(obsConf, serviceInfo, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(dataConf, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	employeeRepo := data.NewEmployeeRepo(dataData, logger)
	employeeUsecase := biz.NewEmployeeUsecase(employeeRepo, logger)
	employeeService := service.NewEmployeeService(employeeUsecase)
	grpcServer := server.NewGRPCServer(serverConf, authConf, observabilityObservability, employeeService, logger)
	healthChecker := server.ProvideHealthChecker(dataData, logger)
	httpServer := server.NewHTTPServer(serverConf, authConf, observabilityObservability, employeeService, healthChecker, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
